# Generated by Django 6.0.7 on 2026-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('registro_profesional', models.CharField(max_length=50, unique=True, verbose_name='Registro Profesional')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para suspender al médico y bloquear nuevas citas.', verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['-activo', 'apellidos'],
            },
        ),
    ]
