# Generated by Django 6.0.7 on 2026-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_subtotal_detallefactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
